### ISSUE TITLE
refresh_token is getting lost during auth.py->reauthorize()->_request_access_token() call

### ISSUE THREAD

**Issue by bktrinadh** [smart-on-fhir/client-py#23]
Hi:
auth.py->_request_access_token() is being called during reauthorize(). What is happening is after login I got a refresh_token and after reauthorize() is called, refresh token is getting set to None, so subsequent reauthorize() fails with an error.. Here is the code snip:

        self.refresh_token = ret_params.get('refresh_token') <-- Assignment before checking..
        if self.refresh_token is not None:
            del ret_params['refresh_token']

Not sure if this is right fix but it checks if the response contains the required value before overwriting..

        refresh_token = ret_params.get('refresh_token')
        if  refresh_token:
            self.refresh_token = refresh_token
            del ret_params['refresh_token']

Exception:
Traceback (most recent call last):
  File "/Users/trinadh/work/.venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/trinadh/work/.venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/trinadh/work/smart_fhir_poc/smart_fhir_poc/fhir_app/views.py", line 640, in create_med_statement
    if smart.reauthorize():
  File "/Users/trinadh/work/.venv/lib/python2.7/site-packages/fhirclient/client.py", line 138, in reauthorize
    self._handle_launch_context(ctx)
  File "/Users/trinadh/work/.venv/lib/python2.7/site-packages/fhirclient/client.py", line 143, in _handle_launch_context
    if 'patient' in ctx:
TypeError: argument of type 'NoneType' is not iterable

Thanks
Trinadh..

**Comment by p2** [comment]
Oh, good catch! Do you want to submit a pull request?

**Comment by bktrinadh** [comment]
Yes sure.. I can..

Thanks
Trinadh..
